export const COLORS = new Map<string, string>([
  ['red', '#ff0000'],
  ['blue', '#0000ff'],
  ['green', '#008000'],
  ['yellow', '#ffff00'],
  ['purple', '#800080'],
  ['orange', '#ffa500'],
  ['pink', '#ffc0cb'],
  ['brown', '#a52a2a'],
  ['black', '#000000'],
  ['white', '#ffffff'],
  ['gray', '#808080'],
  ['cyan', '#00ffff'],
  ['magenta', '#ff00ff'],
  ['lime', '#00ff00'],
  ['indigo', '#4b0082'],
  ['violet', '#8a2be2'],
  ['gold', '#ffd700'],
  ['silver', '#c0c0c0'],
  ['bronze', '#cd7f32'],
  ['teal', '#008080'],
  ['coral', '#ff7f50'],
  ['navy', '#000080'],
  ['maroon', '#800000'],
  ['olive', '#808000'],
  ['mint', '#98ff98'],
  ['lavender', '#e6e6fa'],
])

export const ANIMALS = [
  'lion',
  'tiger',
  'bear',
  'elephant',
  'zebra',
  'giraffe',
  'rhinoceros',
  'hippopotamus',
  'kangaroo',
  'panda',
  'koala',
  'alligator',
  'crocodile',
  'cheetah',
  'leopard',
  'wolf',
  'fox',
  'eagle',
  'hawk',
  'dolphin',
  'whale',
  'shark',
  'octopus',
  'turtle',
  'flamingo',
  'peacock',
  'penguin',
  'gorilla',
  'chimpanzee',
]
